/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListLong } from '../models';
/**
 * FriendInternalApi - axios parameter creator
 * @export
 */
export const FriendInternalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
         * @summary 모든 친구 id 조회 API
         * @param {number} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriendIds: async (memberId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('getFriendIds', 'memberId', memberId)
            const localVarPath = `/api/v2/internal/{memberId}/friend/ids`
                .replace(`{${"memberId"}}`, encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT TOKEN required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FriendInternalApi - functional programming interface
 * @export
 */
export const FriendInternalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FriendInternalApiAxiosParamCreator(configuration)
    return {
        /**
         * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
         * @summary 모든 친구 id 조회 API
         * @param {number} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFriendIds(memberId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFriendIds(memberId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendInternalApi.getFriendIds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FriendInternalApi - factory interface
 * @export
 */
export const FriendInternalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FriendInternalApiFp(configuration)
    return {
        /**
         * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
         * @summary 모든 친구 id 조회 API
         * @param {number} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriendIds(memberId: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListLong> {
            return localVarFp.getFriendIds(memberId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FriendInternalApi - object-oriented interface
 * @export
 * @class FriendInternalApi
 * @extends {BaseAPI}
 */
export class FriendInternalApi extends BaseAPI {
    /**
     * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
     * @summary 모든 친구 id 조회 API
     * @param {number} memberId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendInternalApi
     */
    public getFriendIds(memberId: number, options?: RawAxiosRequestConfig) {
        return FriendInternalApiFp(this.configuration).getFriendIds(memberId, options).then((request) => request(this.axios, this.basePath));
    }
}

