/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../pages/__root'
import { Route as AboutRouteImport } from './../../../pages/about'
import { Route as HeaderLayoutRouteRouteImport } from './../../../pages/_header-layout/route'
import { Route as RiotIndexRouteImport } from './../../../pages/riot/index'
import { Route as HeaderLayoutIndexRouteImport } from './../../../pages/_header-layout/index'
import { Route as SignUpTermsRouteImport } from './../../../pages/sign-up/terms'
import { Route as RiotCallbackRouteImport } from './../../../pages/riot/callback'
import { Route as HeaderLayoutMatchRouteImport } from './../../../pages/_header-layout/match'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRouteRoute = HeaderLayoutRouteRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RiotIndexRoute = RiotIndexRouteImport.update({
  id: '/riot/',
  path: '/riot/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutIndexRoute = HeaderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRouteRoute,
} as any)
const SignUpTermsRoute = SignUpTermsRouteImport.update({
  id: '/sign-up/terms',
  path: '/sign-up/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RiotCallbackRoute = RiotCallbackRouteImport.update({
  id: '/riot/callback',
  path: '/riot/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutMatchRoute = HeaderLayoutMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => HeaderLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/match': typeof HeaderLayoutMatchRoute
  '/riot/callback': typeof RiotCallbackRoute
  '/sign-up/terms': typeof SignUpTermsRoute
  '/': typeof HeaderLayoutIndexRoute
  '/riot': typeof RiotIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/match': typeof HeaderLayoutMatchRoute
  '/riot/callback': typeof RiotCallbackRoute
  '/sign-up/terms': typeof SignUpTermsRoute
  '/': typeof HeaderLayoutIndexRoute
  '/riot': typeof RiotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_header-layout': typeof HeaderLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_header-layout/match': typeof HeaderLayoutMatchRoute
  '/riot/callback': typeof RiotCallbackRoute
  '/sign-up/terms': typeof SignUpTermsRoute
  '/_header-layout/': typeof HeaderLayoutIndexRoute
  '/riot/': typeof RiotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/match'
    | '/riot/callback'
    | '/sign-up/terms'
    | '/'
    | '/riot'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/match' | '/riot/callback' | '/sign-up/terms' | '/' | '/riot'
  id:
    | '__root__'
    | '/_header-layout'
    | '/about'
    | '/_header-layout/match'
    | '/riot/callback'
    | '/sign-up/terms'
    | '/_header-layout/'
    | '/riot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HeaderLayoutRouteRoute: typeof HeaderLayoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  RiotCallbackRoute: typeof RiotCallbackRoute
  SignUpTermsRoute: typeof SignUpTermsRoute
  RiotIndexRoute: typeof RiotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riot/': {
      id: '/riot/'
      path: '/riot'
      fullPath: '/riot'
      preLoaderRoute: typeof RiotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/': {
      id: '/_header-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexRouteImport
      parentRoute: typeof HeaderLayoutRouteRoute
    }
    '/sign-up/terms': {
      id: '/sign-up/terms'
      path: '/sign-up/terms'
      fullPath: '/sign-up/terms'
      preLoaderRoute: typeof SignUpTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riot/callback': {
      id: '/riot/callback'
      path: '/riot/callback'
      fullPath: '/riot/callback'
      preLoaderRoute: typeof RiotCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/match': {
      id: '/_header-layout/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof HeaderLayoutMatchRouteImport
      parentRoute: typeof HeaderLayoutRouteRoute
    }
  }
}

interface HeaderLayoutRouteRouteChildren {
  HeaderLayoutMatchRoute: typeof HeaderLayoutMatchRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
}

const HeaderLayoutRouteRouteChildren: HeaderLayoutRouteRouteChildren = {
  HeaderLayoutMatchRoute: HeaderLayoutMatchRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
}

const HeaderLayoutRouteRouteWithChildren =
  HeaderLayoutRouteRoute._addFileChildren(HeaderLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HeaderLayoutRouteRoute: HeaderLayoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  RiotCallbackRoute: RiotCallbackRoute,
  SignUpTermsRoute: SignUpTermsRoute,
  RiotIndexRoute: RiotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
