/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../pages/__root'
import { Route as TestLoginRouteImport } from './../../../pages/test-login'
import { Route as AboutRouteImport } from './../../../pages/about'
import { Route as HeaderLayoutRouteRouteImport } from './../../../pages/_header-layout/route'
import { Route as RiotIndexRouteImport } from './../../../pages/riot/index'
import { Route as HeaderLayoutIndexRouteImport } from './../../../pages/_header-layout/index'
import { Route as SignUpTermsRouteImport } from './../../../pages/sign-up/terms'
import { Route as RiotCallbackRouteImport } from './../../../pages/riot/callback'
import { Route as HeaderLayoutMatchIndexRouteImport } from './../../../pages/_header-layout/match/index'
import { Route as HeaderLayoutBoardIndexRouteImport } from './../../../pages/_header-layout/board/index'
import { Route as HeaderLayoutUsersUserIdRouteImport } from './../../../pages/_header-layout/users/$userId'

const TestLoginRoute = TestLoginRouteImport.update({
  id: '/test-login',
  path: '/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRouteRoute = HeaderLayoutRouteRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RiotIndexRoute = RiotIndexRouteImport.update({
  id: '/riot/',
  path: '/riot/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutIndexRoute = HeaderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRouteRoute,
} as any)
const SignUpTermsRoute = SignUpTermsRouteImport.update({
  id: '/sign-up/terms',
  path: '/sign-up/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RiotCallbackRoute = RiotCallbackRouteImport.update({
  id: '/riot/callback',
  path: '/riot/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutMatchIndexRoute = HeaderLayoutMatchIndexRouteImport.update({
  id: '/match/',
  path: '/match/',
  getParentRoute: () => HeaderLayoutRouteRoute,
} as any)
const HeaderLayoutBoardIndexRoute = HeaderLayoutBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => HeaderLayoutRouteRoute,
} as any)
const HeaderLayoutUsersUserIdRoute = HeaderLayoutUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => HeaderLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/test-login': typeof TestLoginRoute
  '/riot/callback': typeof RiotCallbackRoute
  '/sign-up/terms': typeof SignUpTermsRoute
  '/': typeof HeaderLayoutIndexRoute
  '/riot': typeof RiotIndexRoute
  '/users/$userId': typeof HeaderLayoutUsersUserIdRoute
  '/board': typeof HeaderLayoutBoardIndexRoute
  '/match': typeof HeaderLayoutMatchIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/test-login': typeof TestLoginRoute
  '/riot/callback': typeof RiotCallbackRoute
  '/sign-up/terms': typeof SignUpTermsRoute
  '/': typeof HeaderLayoutIndexRoute
  '/riot': typeof RiotIndexRoute
  '/users/$userId': typeof HeaderLayoutUsersUserIdRoute
  '/board': typeof HeaderLayoutBoardIndexRoute
  '/match': typeof HeaderLayoutMatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_header-layout': typeof HeaderLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/test-login': typeof TestLoginRoute
  '/riot/callback': typeof RiotCallbackRoute
  '/sign-up/terms': typeof SignUpTermsRoute
  '/_header-layout/': typeof HeaderLayoutIndexRoute
  '/riot/': typeof RiotIndexRoute
  '/_header-layout/users/$userId': typeof HeaderLayoutUsersUserIdRoute
  '/_header-layout/board/': typeof HeaderLayoutBoardIndexRoute
  '/_header-layout/match/': typeof HeaderLayoutMatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/test-login'
    | '/riot/callback'
    | '/sign-up/terms'
    | '/'
    | '/riot'
    | '/users/$userId'
    | '/board'
    | '/match'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/test-login'
    | '/riot/callback'
    | '/sign-up/terms'
    | '/'
    | '/riot'
    | '/users/$userId'
    | '/board'
    | '/match'
  id:
    | '__root__'
    | '/_header-layout'
    | '/about'
    | '/test-login'
    | '/riot/callback'
    | '/sign-up/terms'
    | '/_header-layout/'
    | '/riot/'
    | '/_header-layout/users/$userId'
    | '/_header-layout/board/'
    | '/_header-layout/match/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HeaderLayoutRouteRoute: typeof HeaderLayoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  TestLoginRoute: typeof TestLoginRoute
  RiotCallbackRoute: typeof RiotCallbackRoute
  SignUpTermsRoute: typeof SignUpTermsRoute
  RiotIndexRoute: typeof RiotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-login': {
      id: '/test-login'
      path: '/test-login'
      fullPath: '/test-login'
      preLoaderRoute: typeof TestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riot/': {
      id: '/riot/'
      path: '/riot'
      fullPath: '/riot'
      preLoaderRoute: typeof RiotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/': {
      id: '/_header-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexRouteImport
      parentRoute: typeof HeaderLayoutRouteRoute
    }
    '/sign-up/terms': {
      id: '/sign-up/terms'
      path: '/sign-up/terms'
      fullPath: '/sign-up/terms'
      preLoaderRoute: typeof SignUpTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riot/callback': {
      id: '/riot/callback'
      path: '/riot/callback'
      fullPath: '/riot/callback'
      preLoaderRoute: typeof RiotCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/match/': {
      id: '/_header-layout/match/'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof HeaderLayoutMatchIndexRouteImport
      parentRoute: typeof HeaderLayoutRouteRoute
    }
    '/_header-layout/board/': {
      id: '/_header-layout/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof HeaderLayoutBoardIndexRouteImport
      parentRoute: typeof HeaderLayoutRouteRoute
    }
    '/_header-layout/users/$userId': {
      id: '/_header-layout/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof HeaderLayoutUsersUserIdRouteImport
      parentRoute: typeof HeaderLayoutRouteRoute
    }
  }
}

interface HeaderLayoutRouteRouteChildren {
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
  HeaderLayoutUsersUserIdRoute: typeof HeaderLayoutUsersUserIdRoute
  HeaderLayoutBoardIndexRoute: typeof HeaderLayoutBoardIndexRoute
  HeaderLayoutMatchIndexRoute: typeof HeaderLayoutMatchIndexRoute
}

const HeaderLayoutRouteRouteChildren: HeaderLayoutRouteRouteChildren = {
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
  HeaderLayoutUsersUserIdRoute: HeaderLayoutUsersUserIdRoute,
  HeaderLayoutBoardIndexRoute: HeaderLayoutBoardIndexRoute,
  HeaderLayoutMatchIndexRoute: HeaderLayoutMatchIndexRoute,
}

const HeaderLayoutRouteRouteWithChildren =
  HeaderLayoutRouteRoute._addFileChildren(HeaderLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HeaderLayoutRouteRoute: HeaderLayoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  TestLoginRoute: TestLoginRoute,
  RiotCallbackRoute: RiotCallbackRoute,
  SignUpTermsRoute: SignUpTermsRoute,
  RiotIndexRoute: RiotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
