/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiResponseLong
 */
export interface ApiResponseLong {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLong
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseLong
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseLong
     */
    'code'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLong
     */
    'data'?: number;
}

