/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BoardUpdateResponse } from "./board-update-response";

/**
 *
 * @export
 * @interface ApiResponseBoardUpdateResponse
 */
export interface ApiResponseBoardUpdateResponse {
	/**
	 *
	 * @type {number}
	 * @memberof ApiResponseBoardUpdateResponse
	 */
	status?: number;
	/**
	 *
	 * @type {string}
	 * @memberof ApiResponseBoardUpdateResponse
	 */
	message?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ApiResponseBoardUpdateResponse
	 */
	code?: string;
	/**
	 *
	 * @type {BoardUpdateResponse}
	 * @memberof ApiResponseBoardUpdateResponse
	 */
	data?: BoardUpdateResponse;
}
