/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RejoinResponse } from './rejoin-response';

/**
 * 
 * @export
 * @interface ApiResponseRejoinResponse
 */
export interface ApiResponseRejoinResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseRejoinResponse
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRejoinResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRejoinResponse
     */
    'code'?: string;
    /**
     * 
     * @type {RejoinResponse}
     * @memberof ApiResponseRejoinResponse
     */
    'data'?: RejoinResponse;
}

