/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReportInsertResponse } from './report-insert-response';

/**
 * 
 * @export
 * @interface ApiResponseReportInsertResponse
 */
export interface ApiResponseReportInsertResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseReportInsertResponse
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseReportInsertResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseReportInsertResponse
     */
    'code'?: string;
    /**
     * 
     * @type {ReportInsertResponse}
     * @memberof ApiResponseReportInsertResponse
     */
    'data'?: ReportInsertResponse;
}

