/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 공통 에러 응답 포맷
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof ApiErrorResponse
     */
    'status'?: number;
    /**
     * 에러 메시지
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'message'?: string;
    /**
     * 비즈니스 에러 코드
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'code'?: string;
    /**
     * 응답 데이터 (에러 시 null)
     * @type {object}
     * @memberof ApiErrorResponse
     */
    'data'?: object | null;
}

