/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MatchingFoundResponse } from './matching-found-response';

/**
 * 
 * @export
 * @interface ApiResponseMatchingFoundResponse
 */
export interface ApiResponseMatchingFoundResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseMatchingFoundResponse
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseMatchingFoundResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseMatchingFoundResponse
     */
    'code'?: string;
    /**
     * 
     * @type {MatchingFoundResponse}
     * @memberof ApiResponseMatchingFoundResponse
     */
    'data'?: MatchingFoundResponse;
}

