/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatMessageListResponse } from './chat-message-list-response';

/**
 * 
 * @export
 * @interface ApiResponseChatMessageListResponse
 */
export interface ApiResponseChatMessageListResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseChatMessageListResponse
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseChatMessageListResponse
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseChatMessageListResponse
     */
    'code'?: string;
    /**
     * 
     * @type {ChatMessageListResponse}
     * @memberof ApiResponseChatMessageListResponse
     */
    'data'?: ChatMessageListResponse;
}

