/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FriendRequestResponse } from './friend-request-response';

/**
 * 
 * @export
 * @interface ApiResponseFriendRequestResponse
 */
export interface ApiResponseFriendRequestResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseFriendRequestResponse
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseFriendRequestResponse
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseFriendRequestResponse
     */
    'code'?: string;
    /**
     * 
     * @type {FriendRequestResponse}
     * @memberof ApiResponseFriendRequestResponse
     */
    'data'?: FriendRequestResponse;
}

