/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReportPageResponse } from './report-page-response';

/**
 * 
 * @export
 * @interface ApiResponseReportPageResponse
 */
export interface ApiResponseReportPageResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseReportPageResponse
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseReportPageResponse
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseReportPageResponse
     */
    'code'?: string;
    /**
     * 
     * @type {ReportPageResponse}
     * @memberof ApiResponseReportPageResponse
     */
    'data'?: ReportPageResponse;
}

