/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 차단 유형
 * @export
 * @enum {string}
 */

export const BanType = {
	NONE: "NONE",
	WARNING: "WARNING",
	BAN_1D: "BAN_1D",
	BAN_3D: "BAN_3D",
	BAN_5D: "BAN_5D",
	BAN_1W: "BAN_1W",
	BAN_2W: "BAN_2W",
	BAN_1M: "BAN_1M",
	PERMANENT: "PERMANENT",
} as const;

export type BanType = (typeof BanType)[keyof typeof BanType];
