/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from './game-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';

/**
 * 
 * @export
 * @interface BoardUpdateRequest
 */
export interface BoardUpdateRequest {
    /**
     * 
     * @type {GameMode}
     * @memberof BoardUpdateRequest
     */
    'gameMode': GameMode;
    /**
     * 
     * @type {Position}
     * @memberof BoardUpdateRequest
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof BoardUpdateRequest
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof BoardUpdateRequest
     */
    'wantP': Array<BoardUpdateRequestWantP>;
    /**
     * 
     * @type {Mike}
     * @memberof BoardUpdateRequest
     */
    'mike'?: Mike;
    /**
     * 
     * @type {Array<number>}
     * @memberof BoardUpdateRequest
     */
    'gameStyles': Array<number>;
    /**
     * 게시글 내용 (선택)
     * @type {string}
     * @memberof BoardUpdateRequest
     */
    'contents'?: string;
}

export const BoardUpdateRequestWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type BoardUpdateRequestWantP = typeof BoardUpdateRequestWantP[keyof typeof BoardUpdateRequestWantP];


