/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from "./game-mode";
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from "./mike";
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from "./position";
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from "./tier";

/**
 *
 * @export
 * @interface BoardUpdateResponse
 */
export interface BoardUpdateResponse {
	/**
	 *
	 * @type {number}
	 * @memberof BoardUpdateResponse
	 */
	boardId?: number;
	/**
	 *
	 * @type {number}
	 * @memberof BoardUpdateResponse
	 */
	memberId?: number;
	/**
	 *
	 * @type {number}
	 * @memberof BoardUpdateResponse
	 */
	profileImage?: number;
	/**
	 *
	 * @type {string}
	 * @memberof BoardUpdateResponse
	 */
	gameName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof BoardUpdateResponse
	 */
	tag?: string;
	/**
	 *
	 * @type {Tier}
	 * @memberof BoardUpdateResponse
	 */
	tier?: Tier;
	/**
	 *
	 * @type {number}
	 * @memberof BoardUpdateResponse
	 */
	rank?: number;
	/**
	 *
	 * @type {GameMode}
	 * @memberof BoardUpdateResponse
	 */
	gameMode?: GameMode;
	/**
	 *
	 * @type {Position}
	 * @memberof BoardUpdateResponse
	 */
	mainP?: Position;
	/**
	 *
	 * @type {Position}
	 * @memberof BoardUpdateResponse
	 */
	subP?: Position;
	/**
	 *
	 * @type {Array<Position>}
	 * @memberof BoardUpdateResponse
	 */
	wantP?: Array<Position>;
	/**
	 *
	 * @type {Mike}
	 * @memberof BoardUpdateResponse
	 */
	mike?: Mike;
	/**
	 *
	 * @type {Array<number>}
	 * @memberof BoardUpdateResponse
	 */
	gameStyles?: Array<number>;
	/**
	 *
	 * @type {string}
	 * @memberof BoardUpdateResponse
	 */
	contents?: string;
}
