/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from './game-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from './tier';

/**
 * 
 * @export
 * @interface BoardInsertResponse
 */
export interface BoardInsertResponse {
    /**
     * 
     * @type {number}
     * @memberof BoardInsertResponse
     */
    'boardId': number;
    /**
     * 
     * @type {number}
     * @memberof BoardInsertResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardInsertResponse
     */
    'profileImage': number;
    /**
     * 
     * @type {string}
     * @memberof BoardInsertResponse
     */
    'gameName': string;
    /**
     * 
     * @type {string}
     * @memberof BoardInsertResponse
     */
    'tag': string;
    /**
     * 
     * @type {Tier}
     * @memberof BoardInsertResponse
     */
    'tier': Tier;
    /**
     * 
     * @type {number}
     * @memberof BoardInsertResponse
     */
    'rank': number;
    /**
     * 
     * @type {GameMode}
     * @memberof BoardInsertResponse
     */
    'gameMode': GameMode;
    /**
     * 
     * @type {Position}
     * @memberof BoardInsertResponse
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof BoardInsertResponse
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof BoardInsertResponse
     */
    'wantP': Array<BoardInsertResponseWantP>;
    /**
     * 
     * @type {Mike}
     * @memberof BoardInsertResponse
     */
    'mike': Mike;
    /**
     * 
     * @type {Array<number>}
     * @memberof BoardInsertResponse
     */
    'gameStyles': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof BoardInsertResponse
     */
    'contents'?: string;
}

export const BoardInsertResponseWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type BoardInsertResponseWantP = typeof BoardInsertResponseWantP[keyof typeof BoardInsertResponseWantP];


