/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ChampionStatsResponse } from "./champion-stats-response";
// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from "./game-mode";
// May contain unused imports in some cases
// @ts-ignore
import type { MemberRecentStatsResponse } from "./member-recent-stats-response";
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from "./mike";
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from "./position";
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from "./tier";

/**
 *
 * @export
 * @interface BoardListResponse
 */
export interface BoardListResponse {
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	boardId?: number;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	memberId?: number;
	/**
	 *
	 * @type {string}
	 * @memberof BoardListResponse
	 */
	gameName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof BoardListResponse
	 */
	tag?: string;
	/**
	 *
	 * @type {Position}
	 * @memberof BoardListResponse
	 */
	mainP?: Position;
	/**
	 *
	 * @type {Position}
	 * @memberof BoardListResponse
	 */
	subP?: Position;
	/**
	 *
	 * @type {Array<Position>}
	 * @memberof BoardListResponse
	 */
	wantP?: Array<Position>;
	/**
	 *
	 * @type {Mike}
	 * @memberof BoardListResponse
	 */
	mike?: Mike;
	/**
	 *
	 * @type {string}
	 * @memberof BoardListResponse
	 */
	contents?: string;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	boardProfileImage?: number;
	/**
	 *
	 * @type {string}
	 * @memberof BoardListResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	profileImage?: number;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	mannerLevel?: number;
	/**
	 *
	 * @type {Tier}
	 * @memberof BoardListResponse
	 */
	tier?: Tier;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	rank?: number;
	/**
	 *
	 * @type {GameMode}
	 * @memberof BoardListResponse
	 */
	gameMode?: GameMode;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	winRate?: number;
	/**
	 *
	 * @type {string}
	 * @memberof BoardListResponse
	 */
	bumpTime?: string;
	/**
	 *
	 * @type {Array<ChampionStatsResponse>}
	 * @memberof BoardListResponse
	 */
	championStatsResponseList?: Array<ChampionStatsResponse>;
	/**
	 *
	 * @type {MemberRecentStatsResponse}
	 * @memberof BoardListResponse
	 */
	memberRecentStats?: MemberRecentStatsResponse;
	/**
	 *
	 * @type {Tier}
	 * @memberof BoardListResponse
	 */
	freeTier?: Tier;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	freeRank?: number;
	/**
	 *
	 * @type {Tier}
	 * @memberof BoardListResponse
	 */
	soloTier?: Tier;
	/**
	 *
	 * @type {number}
	 * @memberof BoardListResponse
	 */
	soloRank?: number;
}
