/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChampionStatsResponse } from './champion-stats-response';
// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from './game-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberRecentStatsResponse } from './member-recent-stats-response';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from './tier';

/**
 * 
 * @export
 * @interface BoardByIdResponseForMember
 */
export interface BoardByIdResponseForMember {
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'boardId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'memberId'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BoardByIdResponseForMember
     */
    'isBlocked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BoardByIdResponseForMember
     */
    'isFriend'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'friendRequestMemberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponseForMember
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'profileImage'?: number;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponseForMember
     */
    'gameName'?: string;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponseForMember
     */
    'tag'?: string;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'mannerLevel'?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'mannerRank'?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'mannerRatingCount'?: number;
    /**
     * 
     * @type {Tier}
     * @memberof BoardByIdResponseForMember
     */
    'soloTier'?: Tier;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'soloRank'?: number;
    /**
     * 
     * @type {Tier}
     * @memberof BoardByIdResponseForMember
     */
    'freeTier'?: Tier;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'freeRank'?: number;
    /**
     * 
     * @type {Mike}
     * @memberof BoardByIdResponseForMember
     */
    'mike'?: Mike;
    /**
     * 
     * @type {Array<ChampionStatsResponse>}
     * @memberof BoardByIdResponseForMember
     */
    'championStatsResponseList'?: Array<ChampionStatsResponse>;
    /**
     * 
     * @type {MemberRecentStatsResponse}
     * @memberof BoardByIdResponseForMember
     */
    'memberRecentStats'?: MemberRecentStatsResponse;
    /**
     * 
     * @type {GameMode}
     * @memberof BoardByIdResponseForMember
     */
    'gameMode'?: GameMode;
    /**
     * 
     * @type {Position}
     * @memberof BoardByIdResponseForMember
     */
    'mainP'?: Position;
    /**
     * 
     * @type {Position}
     * @memberof BoardByIdResponseForMember
     */
    'subP'?: Position;
    /**
     * 
     * @type {Array<Position>}
     * @memberof BoardByIdResponseForMember
     */
    'wantP'?: Array<Position>;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'recentGameCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponseForMember
     */
    'winRate'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof BoardByIdResponseForMember
     */
    'gameStyles'?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponseForMember
     */
    'contents'?: string;
}



