/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChampionStatsResponse } from './champion-stats-response';
// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from './game-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberRecentStatsResponse } from './member-recent-stats-response';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from './tier';

/**
 * 
 * @export
 * @interface BoardByIdResponse
 */
export interface BoardByIdResponse {
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'boardId': number;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponse
     */
    'createdAt': string;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'profileImage': number;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponse
     */
    'gameName': string;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponse
     */
    'tag': string;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'mannerLevel': number;
    /**
     * 
     * @type {Tier}
     * @memberof BoardByIdResponse
     */
    'soloTier': Tier;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'soloRank': number;
    /**
     * 
     * @type {Tier}
     * @memberof BoardByIdResponse
     */
    'freeTier': Tier;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'freeRank': number;
    /**
     * 
     * @type {Mike}
     * @memberof BoardByIdResponse
     */
    'mike': Mike;
    /**
     * 
     * @type {Array<ChampionStatsResponse>}
     * @memberof BoardByIdResponse
     */
    'championStatsResponseList': Array<ChampionStatsResponse>;
    /**
     * 
     * @type {MemberRecentStatsResponse}
     * @memberof BoardByIdResponse
     */
    'memberRecentStats'?: MemberRecentStatsResponse;
    /**
     * 
     * @type {GameMode}
     * @memberof BoardByIdResponse
     */
    'gameMode': GameMode;
    /**
     * 
     * @type {Position}
     * @memberof BoardByIdResponse
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof BoardByIdResponse
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof BoardByIdResponse
     */
    'wantP': Array<BoardByIdResponseWantP>;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'recentGameCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardByIdResponse
     */
    'winRate'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof BoardByIdResponse
     */
    'gameStyles': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof BoardByIdResponse
     */
    'contents'?: string;
}

export const BoardByIdResponseWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type BoardByIdResponseWantP = typeof BoardByIdResponseWantP[keyof typeof BoardByIdResponseWantP];


