/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 게임 모드
 * @export
 * @enum {string}
 */

export const GameMode = {
	FAST: "FAST",
	SOLO: "SOLO",
	FREE: "FREE",
	ARAM: "ARAM",
} as const;

export type GameMode = (typeof GameMode)[keyof typeof GameMode];
