/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from './game-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';

/**
 * 
 * @export
 * @interface GuestBoardUpdateRequest
 */
export interface GuestBoardUpdateRequest {
    /**
     * 
     * @type {GameMode}
     * @memberof GuestBoardUpdateRequest
     */
    'gameMode': GameMode;
    /**
     * 
     * @type {Position}
     * @memberof GuestBoardUpdateRequest
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof GuestBoardUpdateRequest
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof GuestBoardUpdateRequest
     */
    'wantP': Array<GuestBoardUpdateRequestWantP>;
    /**
     * 
     * @type {Mike}
     * @memberof GuestBoardUpdateRequest
     */
    'mike'?: Mike;
    /**
     * 게임 스타일 리스트 (선택, 최대 3개)
     * @type {Array<number>}
     * @memberof GuestBoardUpdateRequest
     */
    'gameStyles'?: Array<number>;
    /**
     * 게시글 내용 (선택)
     * @type {string}
     * @memberof GuestBoardUpdateRequest
     */
    'contents'?: string;
    /**
     * 4-16자의 비밀번호를 입력해주세요
     * @type {string}
     * @memberof GuestBoardUpdateRequest
     */
    'password': string;
}

export const GuestBoardUpdateRequestWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type GuestBoardUpdateRequestWantP = typeof GuestBoardUpdateRequestWantP[keyof typeof GuestBoardUpdateRequestWantP];


