/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from "./game-mode";
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from "./mike";
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from "./position";

/**
 *
 * @export
 * @interface GuestBoardInsertRequest
 */
export interface GuestBoardInsertRequest {
	/**
	 *
	 * @type {number}
	 * @memberof GuestBoardInsertRequest
	 */
	boardProfileImage: number;
	/**
	 *
	 * @type {GameMode}
	 * @memberof GuestBoardInsertRequest
	 */
	gameMode: GameMode;
	/**
	 *
	 * @type {Position}
	 * @memberof GuestBoardInsertRequest
	 */
	mainP: Position;
	/**
	 *
	 * @type {Position}
	 * @memberof GuestBoardInsertRequest
	 */
	subP: Position;
	/**
	 *
	 * @type {Array<Position>}
	 * @memberof GuestBoardInsertRequest
	 */
	wantP: Array<Position>;
	/**
	 *
	 * @type {Mike}
	 * @memberof GuestBoardInsertRequest
	 */
	mike?: Mike;
	/**
	 *
	 * @type {Array<number>}
	 * @memberof GuestBoardInsertRequest
	 */
	gameStyles: Array<number>;
	/**
	 * 게시글 내용 (선택)
	 * @type {string}
	 * @memberof GuestBoardInsertRequest
	 */
	contents?: string;
	/**
	 * 게임 내 닉네임
	 * @type {string}
	 * @memberof GuestBoardInsertRequest
	 */
	gameName: string;
	/**
	 * 게임 태그
	 * @type {string}
	 * @memberof GuestBoardInsertRequest
	 */
	tag: string;
	/**
	 * 4-16자의 비밀번호를 입력해주세요
	 * @type {string}
	 * @memberof GuestBoardInsertRequest
	 */
	password: string;
}
