/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from "./game-mode";
// May contain unused imports in some cases
// @ts-ignore
import type { MatchingType } from "./matching-type";
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from "./mike";
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from "./position";

/**
 *
 * @export
 * @interface InitializingMatchingRequest
 */
export interface InitializingMatchingRequest {
	/**
	 *
	 * @type {GameMode}
	 * @memberof InitializingMatchingRequest
	 */
	gameMode: GameMode;
	/**
	 *
	 * @type {Mike}
	 * @memberof InitializingMatchingRequest
	 */
	mike: Mike;
	/**
	 *
	 * @type {MatchingType}
	 * @memberof InitializingMatchingRequest
	 */
	matchingType: MatchingType;
	/**
	 *
	 * @type {Position}
	 * @memberof InitializingMatchingRequest
	 */
	mainP?: Position;
	/**
	 *
	 * @type {Position}
	 * @memberof InitializingMatchingRequest
	 */
	subP?: Position;
	/**
	 *
	 * @type {Array<Position>}
	 * @memberof InitializingMatchingRequest
	 */
	wantP?: Array<Position>;
	/**
	 *
	 * @type {Array<number>}
	 * @memberof InitializingMatchingRequest
	 */
	gameStyleIdList?: Array<number>;
}
