/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BanType } from './ban-type';

/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    'profileImage'?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'accessToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {BanType}
     * @memberof LoginResponse
     */
    'banType'?: BanType;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'banExpireAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'banMessage'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    'banned'?: boolean;
}



