/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 로그인 유형
 * @export
 * @enum {string}
 */

export const LoginType = {
	GENERAL: "GENERAL",
	RSO: "RSO",
} as const;

export type LoginType = (typeof LoginType)[keyof typeof LoginType];
