/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 매칭 상태
 * @export
 * @enum {string}
 */

export const MatchingStatus = {
    FAIL: 'FAIL',
    SUCCESS: 'SUCCESS',
    PENDING: 'PENDING',
    FOUND: 'FOUND',
    QUIT: 'QUIT'
} as const;

export type MatchingStatus = typeof MatchingStatus[keyof typeof MatchingStatus];



