/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GameMode } from './game-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { GameStyleResponse } from './game-style-response';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from './tier';

/**
 * 
 * @export
 * @interface MatchingMemberInfoResponse
 */
export interface MatchingMemberInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof MatchingMemberInfoResponse
     */
    'memberId': number;
    /**
     * 
     * @type {string}
     * @memberof MatchingMemberInfoResponse
     */
    'matchingUuid': string;
    /**
     * 
     * @type {string}
     * @memberof MatchingMemberInfoResponse
     */
    'gameName': string;
    /**
     * 
     * @type {string}
     * @memberof MatchingMemberInfoResponse
     */
    'tag': string;
    /**
     * 
     * @type {Tier}
     * @memberof MatchingMemberInfoResponse
     */
    'soloTier': Tier;
    /**
     * 
     * @type {number}
     * @memberof MatchingMemberInfoResponse
     */
    'soloRank': number;
    /**
     * 
     * @type {Tier}
     * @memberof MatchingMemberInfoResponse
     */
    'freeTier': Tier;
    /**
     * 
     * @type {number}
     * @memberof MatchingMemberInfoResponse
     */
    'freeRank': number;
    /**
     * 
     * @type {number}
     * @memberof MatchingMemberInfoResponse
     */
    'mannerLevel': number;
    /**
     * 
     * @type {number}
     * @memberof MatchingMemberInfoResponse
     */
    'profileImg': number;
    /**
     * 
     * @type {GameMode}
     * @memberof MatchingMemberInfoResponse
     */
    'gameMode': GameMode;
    /**
     * 
     * @type {Position}
     * @memberof MatchingMemberInfoResponse
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof MatchingMemberInfoResponse
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof MatchingMemberInfoResponse
     */
    'wantP': Array<MatchingMemberInfoResponseWantP>;
    /**
     * 
     * @type {Mike}
     * @memberof MatchingMemberInfoResponse
     */
    'mike': Mike;
    /**
     * 
     * @type {Array<GameStyleResponse>}
     * @memberof MatchingMemberInfoResponse
     */
    'gameStyleResponseList': Array<GameStyleResponse>;
}

export const MatchingMemberInfoResponseWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type MatchingMemberInfoResponseWantP = typeof MatchingMemberInfoResponseWantP[keyof typeof MatchingMemberInfoResponseWantP];


