/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ChampionStatsResponse } from "./champion-stats-response";
// May contain unused imports in some cases
// @ts-ignore
import type { GameStyleResponse } from "./game-style-response";
// May contain unused imports in some cases
// @ts-ignore
import type { LoginType } from "./login-type";
// May contain unused imports in some cases
// @ts-ignore
import type { MemberRecentStatsResponse } from "./member-recent-stats-response";
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from "./mike";
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from "./position";
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from "./tier";

/**
 *
 * @export
 * @interface MyProfileResponse
 */
export interface MyProfileResponse {
	/**
	 *
	 * @type {number}
	 * @memberof MyProfileResponse
	 */
	id?: number;
	/**
	 *
	 * @type {number}
	 * @memberof MyProfileResponse
	 */
	profileImg?: number;
	/**
	 *
	 * @type {Mike}
	 * @memberof MyProfileResponse
	 */
	mike?: Mike;
	/**
	 *
	 * @type {string}
	 * @memberof MyProfileResponse
	 */
	email?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MyProfileResponse
	 */
	gameName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MyProfileResponse
	 */
	tag?: string;
	/**
	 *
	 * @type {Tier}
	 * @memberof MyProfileResponse
	 */
	soloTier?: Tier;
	/**
	 *
	 * @type {number}
	 * @memberof MyProfileResponse
	 */
	soloRank?: number;
	/**
	 *
	 * @type {number}
	 * @memberof MyProfileResponse
	 */
	soloWinrate?: number;
	/**
	 *
	 * @type {Tier}
	 * @memberof MyProfileResponse
	 */
	freeTier?: Tier;
	/**
	 *
	 * @type {number}
	 * @memberof MyProfileResponse
	 */
	freeRank?: number;
	/**
	 *
	 * @type {number}
	 * @memberof MyProfileResponse
	 */
	freeWinrate?: number;
	/**
	 *
	 * @type {string}
	 * @memberof MyProfileResponse
	 */
	updatedAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MyProfileResponse
	 */
	championStatsRefreshedAt?: string;
	/**
	 *
	 * @type {Position}
	 * @memberof MyProfileResponse
	 */
	mainP?: Position;
	/**
	 *
	 * @type {Position}
	 * @memberof MyProfileResponse
	 */
	subP?: Position;
	/**
	 *
	 * @type {Array<Position>}
	 * @memberof MyProfileResponse
	 */
	wantP?: Array<Position>;
	/**
	 *
	 * @type {boolean}
	 * @memberof MyProfileResponse
	 */
	isAgree?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof MyProfileResponse
	 */
	isBlind?: boolean;
	/**
	 *
	 * @type {LoginType}
	 * @memberof MyProfileResponse
	 */
	loginType?: LoginType;
	/**
	 *
	 * @type {Array<GameStyleResponse>}
	 * @memberof MyProfileResponse
	 */
	gameStyleResponseList?: Array<GameStyleResponse>;
	/**
	 *
	 * @type {Array<ChampionStatsResponse>}
	 * @memberof MyProfileResponse
	 */
	championStatsResponseList?: Array<ChampionStatsResponse>;
	/**
	 *
	 * @type {MemberRecentStatsResponse}
	 * @memberof MyProfileResponse
	 */
	memberRecentStats?: MemberRecentStatsResponse;
	/**
	 *
	 * @type {boolean}
	 * @memberof MyProfileResponse
	 */
	canRefresh?: boolean;
}
