/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChampionStatsResponse } from './champion-stats-response';
// May contain unused imports in some cases
// @ts-ignore
import type { GameStyleResponse } from './game-style-response';
// May contain unused imports in some cases
// @ts-ignore
import type { LoginType } from './login-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberRecentStatsResponse } from './member-recent-stats-response';
// May contain unused imports in some cases
// @ts-ignore
import type { Mike } from './mike';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';
// May contain unused imports in some cases
// @ts-ignore
import type { Tier } from './tier';

/**
 * 
 * @export
 * @interface OtherProfileResponse
 */
export interface OtherProfileResponse {
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'profileImg': number;
    /**
     * 
     * @type {Mike}
     * @memberof OtherProfileResponse
     */
    'mike': Mike;
    /**
     * 
     * @type {string}
     * @memberof OtherProfileResponse
     */
    'gameName': string;
    /**
     * 
     * @type {string}
     * @memberof OtherProfileResponse
     */
    'tag': string;
    /**
     * 
     * @type {Tier}
     * @memberof OtherProfileResponse
     */
    'soloTier': Tier;
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'soloRank': number;
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'soloWinrate'?: number;
    /**
     * 
     * @type {Tier}
     * @memberof OtherProfileResponse
     */
    'freeTier': Tier;
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'freeRank': number;
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'freeWinrate'?: number;
    /**
     * 
     * @type {string}
     * @memberof OtherProfileResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Position}
     * @memberof OtherProfileResponse
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof OtherProfileResponse
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof OtherProfileResponse
     */
    'wantP': Array<OtherProfileResponseWantP>;
    /**
     * 
     * @type {boolean}
     * @memberof OtherProfileResponse
     */
    'isAgree': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OtherProfileResponse
     */
    'isBlind': boolean;
    /**
     * 
     * @type {LoginType}
     * @memberof OtherProfileResponse
     */
    'loginType': LoginType;
    /**
     * 
     * @type {boolean}
     * @memberof OtherProfileResponse
     */
    'blocked': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OtherProfileResponse
     */
    'friend': boolean;
    /**
     * 
     * @type {number}
     * @memberof OtherProfileResponse
     */
    'friendRequestMemberId'?: number;
    /**
     * 
     * @type {Array<GameStyleResponse>}
     * @memberof OtherProfileResponse
     */
    'gameStyleResponseList': Array<GameStyleResponse>;
    /**
     * 
     * @type {Array<ChampionStatsResponse>}
     * @memberof OtherProfileResponse
     */
    'championStatsResponseList': Array<ChampionStatsResponse>;
    /**
     * 
     * @type {MemberRecentStatsResponse}
     * @memberof OtherProfileResponse
     */
    'memberRecentStats'?: MemberRecentStatsResponse;
    /**
     * 
     * @type {boolean}
     * @memberof OtherProfileResponse
     */
    'canRefresh': boolean;
}

export const OtherProfileResponseWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type OtherProfileResponseWantP = typeof OtherProfileResponseWantP[keyof typeof OtherProfileResponseWantP];


