/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';

/**
 * 
 * @export
 * @interface PositionRequest
 */
export interface PositionRequest {
    /**
     * 
     * @type {Position}
     * @memberof PositionRequest
     */
    'mainP': Position;
    /**
     * 
     * @type {Position}
     * @memberof PositionRequest
     */
    'subP': Position;
    /**
     * 
     * @type {Array<string>}
     * @memberof PositionRequest
     */
    'wantP': Array<PositionRequestWantP>;
}

export const PositionRequestWantP = {
    ANY: 'ANY',
    TOP: 'TOP',
    JUNGLE: 'JUNGLE',
    MID: 'MID',
    ADC: 'ADC',
    SUP: 'SUP'
} as const;

export type PositionRequestWantP = typeof PositionRequestWantP[keyof typeof PositionRequestWantP];


