/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 게임 포지션
 * @export
 * @enum {string}
 */

export const Position = {
	ANY: "ANY",
	TOP: "TOP",
	JUNGLE: "JUNGLE",
	MID: "MID",
	ADC: "ADC",
	SUP: "SUP",
} as const;

export type Position = (typeof Position)[keyof typeof Position];
