/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RejoinResponse
 */
export interface RejoinResponse {
    /**
     * 
     * @type {number}
     * @memberof RejoinResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'gameName': string;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'tag': string;
    /**
     * 
     * @type {number}
     * @memberof RejoinResponse
     */
    'profileImage': number;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'refreshToken': string;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'banType'?: RejoinResponseBanType;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'banMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof RejoinResponse
     */
    'banExpireAt'?: string;
}

export const RejoinResponseBanType = {
    NONE: 'NONE',
    WARNING: 'WARNING',
    BAN_1D: 'BAN_1D',
    BAN_3D: 'BAN_3D',
    BAN_5D: 'BAN_5D',
    BAN_1W: 'BAN_1W',
    BAN_2W: 'BAN_2W',
    BAN_1M: 'BAN_1M',
    PERMANENT: 'PERMANENT'
} as const;

export type RejoinResponseBanType = typeof RejoinResponseBanType[keyof typeof RejoinResponseBanType];


