/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 신고 정렬 순서
 * @export
 * @enum {string}
 */

export const ReportSortOrder = {
    LATEST: 'LATEST',
    OLDEST: 'OLDEST'
} as const;

export type ReportSortOrder = typeof ReportSortOrder[keyof typeof ReportSortOrder];



