/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BanType } from './ban-type';

/**
 * 
 * @export
 * @interface ReportProcessResponse
 */
export interface ReportProcessResponse {
    /**
     * 
     * @type {number}
     * @memberof ReportProcessResponse
     */
    'reportId': number;
    /**
     * 
     * @type {number}
     * @memberof ReportProcessResponse
     */
    'targetMemberId': number;
    /**
     * 
     * @type {BanType}
     * @memberof ReportProcessResponse
     */
    'appliedBanType': BanType;
    /**
     * 
     * @type {string}
     * @memberof ReportProcessResponse
     */
    'banExpireAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportProcessResponse
     */
    'message': string;
}



