/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 신고 경로
 * @export
 * @enum {string}
 */

export const ReportPath = {
    BOARD: 'BOARD',
    CHAT: 'CHAT',
    PROFILE: 'PROFILE'
} as const;

export type ReportPath = typeof ReportPath[keyof typeof ReportPath];



