/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReportType } from './report-type';

/**
 * 
 * @export
 * @interface ReportRequest
 */
export interface ReportRequest {
    /**
     * 
     * @type {Array<ReportType>}
     * @memberof ReportRequest
     */
    'reportCodeList': Array<ReportType>;
    /**
     * 
     * @type {string}
     * @memberof ReportRequest
     */
    'contents'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportRequest
     */
    'pathCode': number;
    /**
     * 
     * @type {number}
     * @memberof ReportRequest
     */
    'boardId'?: number;
}

