/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RiotJoinResponse
 */
export interface RiotJoinResponse {
    /**
     * 
     * @type {number}
     * @memberof RiotJoinResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RiotJoinResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RiotJoinResponse
     */
    'tag': string;
    /**
     * 
     * @type {number}
     * @memberof RiotJoinResponse
     */
    'profileImage': number;
    /**
     * 
     * @type {string}
     * @memberof RiotJoinResponse
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof RiotJoinResponse
     */
    'refreshToken': string;
}

