/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 리그오브레전드 티어
 * @export
 * @enum {string}
 */

export const Tier = {
	UNRANKED: "UNRANKED",
	IRON: "IRON",
	BRONZE: "BRONZE",
	SILVER: "SILVER",
	GOLD: "GOLD",
	PLATINUM: "PLATINUM",
	EMERALD: "EMERALD",
	DIAMOND: "DIAMOND",
	MASTER: "MASTER",
	GRANDMASTER: "GRANDMASTER",
	CHALLENGER: "CHALLENGER",
} as const;

export type Tier = (typeof Tier)[keyof typeof Tier];
